### ISSUE TITLE
Update in Maven

### ISSUE THREAD

**Issue by GrenderG** [the-blue-alliance/spectrum#1]
Hello, you should update this library in Maven, the version differs from the source code hosted in GitHub.

Thanks.

**Comment by nwalters512** [comment]
I was making some breaking changes to the API, I was waiting until I finished with those to release a new version. I'll get it updated as soon as I can!

**Comment by nwalters512** [comment]
v0.2.1 has been uploaded to bintray and is being processed at maven central.
