### ISSUE TITLE
Color preview doesn't fade when SpectrumPreference is disabled

### ISSUE THREAD

**Issue by francoiscampbell** [the-blue-alliance/spectrum#10]
When the preference is disabled with `android:dependency`, I'd expect the preview circle to fade like the text, but currently it stays the same.

![](https://i.imgur.com/Ntowta4.png)

**Comment by nwalters512** [comment]
I wasn't sure about the best way to handle that. Would it make most sense to just change to a light gray, like the color of the disabled text?

**Comment by francoiscampbell** [comment]
What about changing the alpha of the color?

**Comment by nwalters512** [comment]
That would break if the color is white (or very light). Also, "fading" a color only really means something if you have the original to compare it with. Fading a super-sturated green to a slightly less-saturated green when they can't even see the original color wouldn't have much meaning to the user.

**Comment by francoiscampbell** [comment]
Maybe the alpha amount could be dependent on the color?

I've tried it and a slight alpha seems to be OK, something around 150 is enough to show a slight white overlay but the color is still visible. Here's what it looks like:

![](https://i.imgur.com/i7aB2O8.png?1)
![](https://i.imgur.com/xf04Qev.png?1)
![](https://i.imgur.com/xhmcNiq.png?1)
![](https://i.imgur.com/XVzuKNi.png?1)

**Comment by nwalters512** [comment]
The problem there is I can't tell the color is faded; to me, it just looks like another color the user selected. You or I may be able to say "well sure it's faded; the preference is disabled" but the average user might not know that.

I think coloring the circle gray is the best approach; in a list of disabled items, it'll match the color of any check boxes/switches that are near it in the list. I don't think it's that important to convey which color is actually selected in the disabled state.

**Comment by francoiscampbell** [comment]
Fair enough, I hadn't considered that. The point about grey matching the checkboxes is cool. Check #11

**Comment by nwalters512** [comment]
The fix for this is live with v0.4.0!
