### ISSUE TITLE
Selecting multiple colors

### ISSUE THREAD

**Issue by wzieba** [the-blue-alliance/spectrum#22]
Great library, thank you 😃 

Idea for future feature - it would be nice if we could choose multiple colors in a single dialog.

**Comment by nwalters512** [comment]
Glad you're enjoying it!

What's the use case where choosing multiple colors at once would be useful?

**Comment by wzieba** [comment]
In my particular case I need to get few colors from user and send it to server (three favorites colors). I've done this by creating three dialogs, and it's not very bad. Bigger problem is general case I thought about.

General case is filtering content - most of online shop has this option: "show products only in those colors". Then you should choose not only one, but few colors from dialog.

**Comment by nwalters512** [comment]
Ah, those are indeed valid use cases. That would be a good thing to add to Spectrum.

Do you want to take a stab at it? Otherwise, I can add it to my backlog of things to do.

**Comment by wzieba** [comment]
To be honest with you - I haven't got any experience with building libraries but I would like to take part in Spectrum. I'll try do my best but until end of June I haven't got any free time. Is it ok to start then?

**Comment by nwalters512** [comment]
Depending on how much free time I have, I may end up doing this myself to expedite things. I'd love your input on the API design for this though!
