### ISSUE TITLE
Typo in method name: "Chaxnged"

### ISSUE THREAD

**Issue by victorhurdugaci** [the-blue-alliance/spectrum#28]
`onSelectedColorChaxnged` in https://github.com/the-blue-alliance/spectrum/blob/8d1e5f1818613dfb0c35948bed26394fbc9096ce/spectrum/src/main/java/com/thebluealliance/spectrum/SpectrumPalette.java#L291

**Comment by nwalters512** [comment]
Ah, good catch! Would you be able to submit a PR to fix that?

**Comment by victorhurdugaci** [comment]
Sure. I can do that during the weekend

**Comment by victorhurdugaci** [comment]
It took me more than I was expecting to get back to this but I finally sent a PR :)

**Comment by nwalters512** [comment]
Thanks! I'll include that in the next release. I won't do one just yet since this is a minor but technically breaking change.
