### ISSUE TITLE
Get number of columns

### ISSUE THREAD

**Issue by ghost** [the-blue-alliance/spectrum#31]
It would be great if there is a way to get variable "mNumColumns", because sometimes I want to change number of colors dynamically (depending on view width).
I created subclass of SpectrumPalette,  used reflection to obtain the value, and it works perfectly. But it's not smart.

If there's protected method to get mNumColumns, subclass don't have to use reflection.
If there's  a Listener to notify of column count, I don't have to make subclass.

**Comment by nwalters512** [comment]
A listener would probably be the best way to achieve this, as the number of columns is calculated "asynchronously" (aka there's no guarantee of when the column count will be available) during the layout and measure phase. We could add an `OnColumnCountChangeListener` interface and corresponding `setOnColumnCountChangeListener(...)` methods.

**Comment by ghost** [comment]
Sorry for my late reply.

After thinking, I decided not to change number of colors dynamically, because it's not good UI.
Number of colors changes when screen rotated.

Instead, I will call setFixedColumnCount(int) depending on portrait width, so listener will be no longer needed.

Thank you.
