### ISSUE TITLE
SpectrumPalette item size won't "fit" requested height

### ISSUE THREAD

**Issue by Shailevy** [the-blue-alliance/spectrum#32]
If I state the height of a SpectrumPalette in DP the items will get "cut" instead of adapting to my requested height

I I state a column count (I want 8 color in a single row, like in Google Keep) than it will also be sliced on the side

![image](https://cloud.githubusercontent.com/assets/254902/21139368/33f2ff4a-c13b-11e6-9939-12a72a7edeb8.png)

**Comment by nwalters512** [comment]
I think this specific use case is outside the scope of this library. If you just want 8 colors displayed side-by-side, I think you're best off writing that component yourself. That's a pretty easy one: just 8 weighed views in a horizontal `LinearLayout`.

**Comment by Shailevy** [comment]
I know it's easy to write and that's what i will do. I just wanted to let you know about the buggy behaviour

**Comment by nwalters512** [comment]
Thanks for the heads up. Probably not much I can do about the vertical clipping - this component isn't really meant to work in a height constrained space.

Regarding horizontal clipping with a big column count, what do you think is the best way to handle that: ignore it if it would overflow horizontally, or shrink the color circles to fit more in a row?
