### ISSUE TITLE
Feature request: Allow styling of the AlertDialog

### ISSUE THREAD

**Issue by dkneller** [the-blue-alliance/spectrum#33]
The standard AlertDialog.Builder can be constructed with a themeResId to pass in a theme:
    public static class Builder {
        public Builder(Context context) {
        }

        public Builder(Context context, int themeResId) {
        }
If no themeResId is provided the Dialog picks up the theme from the parent Activity's "alertDialogTheme" style item.  But this is Activity-wide so will cause problems if different AlertDialogs need different styling.

It would be nice if we could provide a themeResId to the SpectrumDialog.Builder so that that theme can be passed to the constructed AlertDialog.  This seems like an easy extension of SpectrumDialog.Builder.

**Comment by nwalters512** [comment]
Check out #34, did I miss anything?
