### ISSUE TITLE
Support library update

### ISSUE THREAD

**Issue by Tom-Horvat** [the-blue-alliance/spectrum#37]
Please update the support library version for `com.android.support:preference-v7:23.4.0` to `com.android.support:preference-v7:25.2.0`. I am experiencing a clash due to updating own projects' support libraries.

**Comment by BennyKok** [comment]
My current temporary solution is to do this `compile 'com.thebluealliance:spectrum:+'` to get away the error, hoping no crashes will happen

Oh sorry I mixed up, now using this `//noinspection GradleCompatible` can be able to compile

**Comment by Tom-Horvat** [comment]
For now, I am using a local copy of the library with updated dependencies :) I will be watching the thread for a new update though.

**Comment by smejkal** [comment]
You should exclude the Support Library:

compile ('com.thebluealliance:spectrum:0.7.1') { exclude group: 'com.android.support' }

**Comment by sir-boformer** [comment]
Thanks for the tip!
