### ISSUE TITLE
Border around white color or make dialog bg customizable

### ISSUE THREAD

**Issue by tomredman** [the-blue-alliance/spectrum#6]
Awesome library!

Would be cool to have the white color circle outlined :)

**Comment by nwalters512** [comment]
Thanks!

It probably makes sense to have all very light colors outlined, not just strictly white. I could repurpose [this chunk of code](https://github.com/the-blue-alliance/spectrum/blob/master/spectrum/src/main/java/com/thebluealliance/spectrum/internal/ColorItem.java#L152) to filter for very light colors and automatically apply a border in that case.

**Comment by svsorokina** [comment]
yes, I need this too :)

**Comment by RocketRider** [comment]
But then you should also add a white outlining around dark colors, think about a night mode.
Not sure how this would look...

**Comment by nwalters512** [comment]
A dark theme would be an interesting option. That's something for another issue though.

**Comment by RocketRider** [comment]
It does work as it is, I use it in an app with dark/night mode. But if you will add only black outlinings it would not be perfect...
I'm currently working on your library, I just added the outlining feature. Take a look into my fork. 
https://github.com/RocketRider/spectrum/

I will add one more thing, then I will make a pull request, in the hope you will add my changes.

**Comment by nwalters512** [comment]
Resolved in #7
