### ISSUE TITLE
Palette rows and columns

### ISSUE THREAD

**Issue by dGorod** [the-blue-alliance/spectrum#8]
Hello!
First, want to thank you for great lib.

But found an issue. I think attached screenshots says everything. 
Problem is that I place colors in some order. But when available screen height too small everything ruins. Thinking about some setters for strict rows and columns count...

![device-2016-04-25-172910](https://cloud.githubusercontent.com/assets/1834315/14787426/ee8ef5c0-0b0b-11e6-9909-a203739ae528.png)
![device-2016-04-25-172931](https://cloud.githubusercontent.com/assets/1834315/14787427/ee96bc42-0b0b-11e6-8860-4d0f203afc59.png)

**Comment by nwalters512** [comment]
Yeah, the dialog currently autosizes itself. I've been meaning to add a way to sex a fixed number of columns. I'm not sure about a fixed number of rows though, can you explain how you'd like that to work and when you'd want to use that?

**Comment by dGorod** [comment]
@nwalters512 emmm... just was a thought :)  Yes, rows has no sense. Columns will fix such situation.
Do you have any plans to add "fixed number columns" feature in near time?

**Comment by nwalters512** [comment]
I can probably get if done in the next few days! I'll put up a PR when it's done so you can check out my implementation.

**Comment by nwalters512** [comment]
@dGorod check out PR #9!

**Comment by nwalters512** [comment]
This is now live in v0.3.0 on Bintray.

**Comment by dGorod** [comment]
Thanks again for fast response.
Does READ.ME section requires update? It still declares in text "0.2.1" as last version.

**Comment by nwalters512** [comment]
I just fixed that! Thanks for pointing it out.
